using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

/// <summary>
/// Displays one baked trait-tree connection sprite and dims it according to whether its
/// prerequisite nodes are unlocked. The sprite itself is generated by TraitTreeUI.
/// </summary>
[RequireComponent(typeof(Image))]
public class TraitConnectionUI : MonoBehaviour
{
    public enum ConnectionState
    {
        Disabled,   // Prerequisites not met
        Enabled,    // Prerequisite met, target can be unlocked
        Activated   // Prerequisite unlocked
    }

    private const float DisabledBrightness = 0.05f;
    private const float EnabledBrightness = 0.3f;
    private const float ActivatedBrightness = 1f;

    private Image image;
    private Color baseColor = Color.white;
    private string[] fromNodeIDs = new string[0];

    private void Awake() => CacheImage();

    private void CacheImage()
    {
        if (image == null)
            image = GetComponent<Image>();
    }

    /// <summary>
    /// Bind the generated path sprite and the prerequisite nodes that light this path up.
    /// </summary>
    public void Initialize(Sprite connectionSprite, Color color, string[] prerequisiteNodeIDs)
    {
        CacheImage();

        fromNodeIDs = prerequisiteNodeIDs ?? new string[0];
        color.a = 1f;
        baseColor = color;

        if (image != null)
        {
            image.sprite = connectionSprite;
            image.type = Image.Type.Simple;
            image.preserveAspect = false;
            image.raycastTarget = false;
        }

        UpdateVisualState(ConnectionState.Disabled);
    }

    /// <summary>
    /// A path lights up once any of its prerequisite nodes is unlocked.
    /// Paths with no prerequisites are always lit.
    /// </summary>
    public void UpdateState(HashSet<string> unlockedNodeIDs)
    {
        UpdateVisualState(IsAnyPrerequisiteUnlocked(unlockedNodeIDs)
            ? ConnectionState.Activated
            : ConnectionState.Disabled);
    }

    public void UpdateVisualState(ConnectionState state)
    {
        CacheImage();
        if (image == null)
            return;

        float brightness = state switch
        {
            ConnectionState.Activated => ActivatedBrightness,
            ConnectionState.Enabled => EnabledBrightness,
            _ => DisabledBrightness
        };

        // The baked sprite already carries the connection colour, so state tinting is greyscale.
        Color tint = Color.white * brightness;
        tint.a = baseColor.a;
        image.color = tint;
    }

    public string[] GetFromNodeIDs() => fromNodeIDs;

    private bool IsAnyPrerequisiteUnlocked(HashSet<string> unlockedNodeIDs)
    {
        if (fromNodeIDs.Length == 0)
            return true;

        if (unlockedNodeIDs == null)
            return false;

        foreach (string nodeID in fromNodeIDs)
        {
            if (!string.IsNullOrEmpty(nodeID) && unlockedNodeIDs.Contains(nodeID))
                return true;
        }

        return false;
    }
}
